echo Cleaning up...
#rm -r build

echo Building MyExecutable independently...
gcc -F/Users/forderud/VBoxShare/UnixSharedLib/embed-file/mac-framework/build/MyDynFramework -framework MyDynFramework -o MyExecutable Main.cpp -v
