echo Cleaning up...
rm -r build install

echo Building projects...
mkdir build
cmake -S . -B build
cmake --build build

echo Installing projects...
cmake --install build --prefix install

echo Running MyExecutable...
build/MyExecutable/MyExecutable
